name: AWS Terraform Apply Reusable

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
       
jobs:
  aws-terraform-noinfrachange-reusable:
    name: 'AWS Terraform No Infrastructure Change - Reusable'
    runs-on: ubuntu-latest
    #runs-on: self-hosted 
    #environment:  #Here is the name of your environment
           
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install nodejs
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Install Terraform CLI and configure the Terraform CLI configuration file
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      # Initialize working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format and style
      - name: Terraform Format
        id: fmt
        run: terraform fmt

      # Validates the configuration
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color   

      # Evaluates and generates an execution plan for Terraform
      - name: Terraform Plan
        id: plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: "."
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -no-color

      # On push to master, build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '.'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
