name: 'AWS-Terraform-NoInfraChangeSteps'

on:
  push:
    branches: [ $default-branch ]
  pull_request: 
    branches: [ $default-branch ]
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      
 
jobs:
  aws-terraform-noinfrachange-reusable:
    name: 'AWS Terraform No Infrastructure Change - Reusable'
    runs-on: self-hosted 
#    environment:  #Here is the name of your environment
           
    steps:
    # Checkout the repository 
    - name: Checkout code
      uses: actions/checkout@v2

    # Install nodejs
    - uses: actions/setup-node@v2
      with:
          node-version: '14'
          
    # Install Terraform CLI and configure the Terraform CLI configuration file
    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1
  

      # On push to master, build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: '.'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
